
-- TASK 1: CONNECTION VERIFICATION
SELECT '========== TASK 1: CONNECTION VERIFICATION ==========' AS STEP;

SELECT CURRENT_USER() AS CURRENT_USER;
SELECT CURRENT_ROLE() AS CURRENT_ROLE;
SELECT CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE;
SELECT CURRENT_DATABASE() AS CURRENT_DATABASE;
SELECT CURRENT_SCHEMA() AS CURRENT_SCHEMA;

-- TASK 2: CREATION OF SNOWFLAKE OBJECTS
SELECT '========== TASK 2: CREATING SNOWFLAKE OBJECTS ==========' AS STEP;

CREATE OR REPLACE DATABASE TUTORIAL_DB;
CREATE OR REPLACE SCHEMA TUTORIAL_DB.TUTORIAL_SCHEMA;

CREATE OR REPLACE WAREHOUSE TUTORIAL_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

USE DATABASE TUTORIAL_DB;
USE SCHEMA TUTORIAL_SCHEMA;
USE WAREHOUSE TUTORIAL_WH;

CREATE OR REPLACE TABLE EMPLOYEES (
    EMP_ID INTEGER,
    EMP_NAME VARCHAR(100),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10,2),
    JOINING_DATE DATE
);

CREATE OR REPLACE STAGE MY_STAGE;

SHOW DATABASES LIKE 'TUTORIAL%';
SHOW SCHEMAS IN DATABASE TUTORIAL_DB;
SHOW WAREHOUSES LIKE 'TUTORIAL%';
SHOW TABLES IN SCHEMA TUTORIAL_SCHEMA;
SHOW STAGES IN SCHEMA TUTORIAL_SCHEMA;

-- Insert Sample Records
INSERT INTO EMPLOYEES VALUES
(101, 'John Doe', 'Engineering', 75000.00, '2023-01-15'),
(102, 'Jane Smith', 'Marketing', 65000.00, '2023-02-20'),
(103, 'Bob Johnson', 'Engineering', 85000.00, '2023-03-10'),
(104, 'Alice Brown', 'Sales', 70000.00, '2023-04-05'),
(105, 'Charlie Wilson', 'HR', 55000.00, '2023-05-12');

SELECT 'INITIAL DATA' AS STEP, * FROM EMPLOYEES ORDER BY EMP_ID;

-- INSERT
INSERT INTO EMPLOYEES VALUES
(106, 'David Lee', 'IT', 80000.00, '2023-06-01');

-- UPDATE
UPDATE EMPLOYEES
SET SALARY = SALARY * 1.10
WHERE DEPARTMENT = 'Engineering';

-- DELETE
DELETE FROM EMPLOYEES
WHERE EMP_ID = 106;

SELECT 'AFTER CRUD OPERATIONS' AS STEP, * 
FROM EMPLOYEES ORDER BY EMP_ID;


-- TASK 3: DATA LOADING
SELECT '========== TASK 3: DATA LOADING ==========' AS STEP;

CREATE OR REPLACE TABLE LOADED_EMPLOYEES (
    EMP_ID INTEGER,
    EMP_NAME VARCHAR(100),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10,2),
    JOINING_DATE DATE
);

CREATE OR REPLACE STAGE EMPLOYEE_STAGE;

LIST @EMPLOYEE_STAGE;

COPY INTO LOADED_EMPLOYEES
FROM @EMPLOYEE_STAGE
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

SELECT 'DATA AFTER LOADING' AS STEP, *
FROM LOADED_EMPLOYEES ORDER BY EMP_ID;

SELECT COUNT(*) AS TOTAL_RECORDS
FROM LOADED_EMPLOYEES;

-- TASK 4: SNOWFLAKE TIME TRAVEL
SELECT '========== TASK 4: TIME TRAVEL ==========' AS STEP;

SELECT 'CURRENT DATA' AS STEP, *
FROM EMPLOYEES ORDER BY EMP_ID;

-- Make changes
UPDATE EMPLOYEES
SET SALARY = SALARY * 1.10
WHERE DEPARTMENT = 'Engineering';

DELETE FROM EMPLOYEES
WHERE EMP_ID IN (104, 105);

SELECT 'AFTER CHANGES' AS STEP, *
FROM EMPLOYEES ORDER BY EMP_ID;

-- WAIT APPROXIMATELY 60 SECONDS BEFORE RUNNING BELOW

SELECT 'TIME TRAVEL - 60 SECONDS AGO' AS STEP, *
FROM EMPLOYEES
BEFORE (OFFSET => -60)
ORDER BY EMP_ID;

-- TASK 5: DATA RECOVERY USING TIME TRAVEL
SELECT '========== TASK 5: DATA RECOVERY ==========' AS STEP;

-- Find deleted records
SELECT 'DELETED RECORDS' AS STEP, *
FROM EMPLOYEES
BEFORE (OFFSET => -60)
WHERE EMP_ID IN (104, 105)
ORDER BY EMP_ID;

-- Recover deleted records
INSERT INTO EMPLOYEES
SELECT *
FROM EMPLOYEES
BEFORE (OFFSET => -60)
WHERE EMP_ID IN (104, 105);

-- Verify recovery
SELECT 'AFTER RECOVERY' AS STEP, *
FROM EMPLOYEES ORDER BY EMP_ID;

SELECT COUNT(*) AS TOTAL_RECORDS
FROM EMPLOYEES;
